### ISSUE TITLE
Region white-matter enrichment trends

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#125]
<img width="730" alt="Screen Shot 2022-08-12 at 1 43 05 PM" src="https://user-images.githubusercontent.com/2288213/184450195-5eeb8d9d-4078-4993-9547-25db313145d8.png">

From the snRNA-seq data so far, we've seen that the `post` region samples (posterior) seem to have higher proportions of oligos and other white-matter enriched genes. Note that this is a subset (n = 19) of the 30 spatial samples we have. But with those n = 19, we could make a scatterplot comparing the proportion of WM spots observed in the spatial data (screenshot incorrectly says GM) vs the proportion of oligos (and similarly for other cell types) in the snRNA-seq data. Then color the samples by region (ant, mid, post). It could be that we have 3 different lines, or maybe all 3 lines have the same slope but different intercepts.

To extract the proportion of WM, we can use the `k = 2` BayesSpace results from https://github.com/LieberInstitute/spatialDLPFC/blob/main/plots/03_BayesSpace/polychrome_vis_grid_clus_sfigu_BayesSpace_k2.pdf where cluster 1 was WM if I remember correctly. The SPE at `/dcs04/lieber/lcolladotor/spatialDLPFC_LIBD4035/spatialDLPFC/processed-data/rdata/spe/01_build_spe/spe_filtered_final_with_clusters.Rdata` likely has this info already. If not, you can use http://research.libd.org/spatialLIBD/reference/cluster_import.html (Nick has used it).

<img width="1448" alt="GoogleDoc_Screen Shot 2022-07-28 at 4 31 06 PM" src="https://user-images.githubusercontent.com/2288213/184450711-b55b948e-81fa-419a-9c68-5ea437d0d10a.png">

<img width="699" alt="Screen Shot 2022-08-12 at 6 06 36 PM" src="https://user-images.githubusercontent.com/2288213/184450786-a9b49983-9dd9-4b37-a836-b71ce68aab00.png">

**Comment by lcolladotor** [comment]
I know this is the least important open issue we have, but well, at some point, I'd like to see these plots. This could be done after our bioRxiv submission though.

**Comment by lcolladotor** [comment]
> without SP2806, 16, 17, 20 and 28 instead of Sp02D01
from https://github.com/LieberInstitute/spatialDLPFC/issues/140#issuecomment-1363428898

**Comment by lcolladotor** [comment]
<img width="953" alt="Screenshot 2023-02-13 at 10 19 01 AM" src="https://user-images.githubusercontent.com/2288213/218512916-8271e6b7-1bb7-45d7-b734-14e921bcfd1d.png">

The current plot at https://github.com/LieberInstitute/spatialDLPFC/blob/main/plots/spot_deconvo/05-shared_utilities/prop_WM_position_scatter.pdf is with Ambiguous being part of the %. Can you make it again without it? (Have the 2 versions)

**Comment by lcolladotor** [comment]
Do you have updates on this one @Nick-Eagles?

**Comment by Nick-Eagles** [comment]
I made [the new version](https://github.com/LieberInstitute/spatialDLPFC/blob/main/plots/spot_deconvo/05-shared_utilities/prop_WM_position_scatter_no_ambig.pdf), and the oligos look a little better (more correlated, as expected)

**Comment by lcolladotor** [comment]
Thanks Nick. We discussed this plot today in the deconvolution meeting and will likely use a version of this (with the RNAscope / HALO data too) for the deconvolution commentary paper.
