### ISSUE TITLE
Add tissue imperfections to R object + spatialLIBD app

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#137]
- [x] Get all the CSV files from Kristen's manual annotation of tissue imperfections (folds and the like)
- [x] Import them and put them together as a single CSV file (version control it here)
- [x] Update https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/analysis/01_build_spe/03_add_deconvolution.R
- [x] Re-deploy the `spatialLIBD` apps

**Comment by lcolladotor** [comment]
Do you have any updates on this @Nick-Eagles?

**Comment by Nick-Eagles** [comment]
I wrote working code to add the wrinkle and layer annotation to the SPE object [here](https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/spot_deconvo/05-shared_utilities/13-add_to_spe_nonIF.R), and I'll aim to integrate/ move this code to your shiny deployment script as we discussed by the end of today. Are you still interested in putting the CSVs together as one CSV (my current code handles the files separately as I received them)?

**Comment by lcolladotor** [comment]
We don't need to put the CSVs together into one file. It's ok to have multiple ones. We do want to have a single R object though

**Comment by Nick-Eagles** [comment]
I updated (but did not fully run) [the R script](https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/analysis/01_build_spe/03_add_deconvolution.R), which will add the `colData` columns `wrinkle_type` and `manual_layer_label`. Let me know if I should run the script (and overwrite the session info at the bottom) or help out with the deployment.

**Comment by Nick-Eagles** [comment]
I now see your slack comment about updating the `lobstr` info and documenting the new variable names, so I'll run the script and do that.

**Comment by lcolladotor** [comment]
Thanks Nick! Yup, let me know once you are done re-making this SPE object, thanks!

**Comment by Nick-Eagles** [comment]
It's ready to deploy!

**Comment by lcolladotor** [comment]
Cool, thanks Nick!
