### ISSUE TITLE
Add Melissa' & Prashanthi's code to this repo

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#139]
Likely under https://github.com/LieberInstitute/spatialDLPFC/tree/main/code. It might a major new directory there or it could be at https://github.com/LieberInstitute/spatialDLPFC/tree/main/code/analysis like @boyiguo1's `15_cell_composition` one.

Melissa, check https://github.com/LieberInstitute/template_project for more on our code organization structure.

While your code will likely not rely on `here` and access to files locally, it'd be nice to have it somewhere on this repo.

Thanks!

**Comment by lcolladotor** [comment]
@prashanthi-ravichandran feel free to meet with @Nick-Eagles if you need help with this. Thanks!

**Comment by lcolladotor** [comment]
@Nick-Eagles I think that you were helping with this one, right?

**Comment by Nick-Eagles** [comment]
Yes-- this is actually done (the scripts are [here](https://github.com/LieberInstitute/spatialDLPFC/tree/main/code/qc_artifact)), and I forgot to update this issue. I'll close now.
