### ISSUE TITLE
Supplementary Table Export

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/spatialDLPFC#141]
order may change depending on cross ref
- [x] Table S1. Demographics of donors included in the study. (stabl_demo)
- [x] Table S2. Summary of DEGs for ANOVA model at broad and fine resolution. (stabl_deg_anova)
- [x] Table S3. Summary of DEGs for enrichment model at broad and fine resolution. (stabl_deg_enrich)
- [x] Table S4. Summary of DEGs for pairwise model at broad and fine resolution. (stabl_deg_pair)
- [x] Table S5. Summary of DEGs across Ant, Mid, Post positions for gray matter. (stabl_deg_postion)
- [x] Table S9. LR pairs from LIANA @boyiguo1 (stable_liana)
- [x] Table S10. Summary of ligand-receptor pairs associated with SCZ genetic risk association. Melissa (stable_lr_scz)

**Comment by boyiguo1** [comment]
FYI, I created another folder for Melissa's Table S10 (moving from `stabl_demo` to `stabl_lr_scz` on OneDrive)

**Comment by lcolladotor** [comment]
@lahuuki @Nick-Eagles I'm done with my tables (Tables S1 through S5). Dunno if you are done with yours. If you are, we can close this issue then.

**Comment by lcolladotor** [comment]
<img width="836" alt="Screenshot 2023-02-14 at 11 40 28 AM" src="https://user-images.githubusercontent.com/2288213/218815305-0beca30e-a737-45a1-9da8-f44a1d2e1073.png">

@boyiguo1 can you help clarify why there's another Table S10 in the `stabl_demo` directory on OneDrive? Thanks! Just trying to avoid any confusion. Maybe your OneDrive changes haven't been synched yet?

**Comment by boyiguo1** [comment]
I believe Melissa originally put the file Table S10 in `stabl_demo`. I moved that to a new folder `stabl_lr_scz` (matched with cross-ref), which didn't sync to the cloud. But now it should be good.

**Comment by lcolladotor** [comment]
Thanks Boyi! 

I wanted to make sure we had the right file =)
