### ISSUE TITLE
Provide anndata files out of the box

### ISSUE THREAD

**Issue by chaichontat** [LieberInstitute/spatialDLPFC#142]
From the info page, 

> You can use the [zellkonverter](https://bioconductor.org/packages/zellkonverter/) Bioconductor package to convert any of them into Python [AnnData](https://anndata.readthedocs.io/en/latest/) objects. If you browse our code, you can find examples of such conversions.

Considering that this is most likely a common operation, would it be possible for you to provide the converted `h5ad` files directly?

**Comment by lcolladotor** [comment]
Providing 2 versions of the files means more maintenance work in the future to make sure they are in sync. It's fairly easy to convert the `SpatialExperiment` objects thanks to `zellkonverter`, so I don't see a point to change this.

If you want, you can also use Globus to access the `h5ad` files Nick created along the way. But that's more for advanced users and in that case, we don't create an expectation that those files are always updated.
