### ISSUE TITLE
manual annotation

### ISSUE THREAD

**Issue by JiawenChenn** [LieberInstitute/spatialDLPFC#143]
Hi, 

Thanks for organizing the data. I have tried to use the spatialDLPFC_Visium data downloaded using spatialLIBD package. I saw a discussion about the manual annotation in the data. Just want to confirm whether I am using the right name for the annotation.

```
> table(spe@colData$sample_id, spe@colData$manual_layer_label)
             
              Layer 1 Layer 2 Layer 3 Layer 4 Layer 5 Layer 6   WM
  Br2720_ant        0       0       0       0       0       0    0
  Br2720_mid        0       0       0       0       0       0    0
  Br2720_post       0       0       0       0       0       0    0
  Br2743_ant        0       0       0       0       0       0    0
  Br2743_mid        0       0       0       0       0       0    0
  Br2743_post       0       0       0       0       0       0    0
  Br3942_ant        0       0       0       0       0       0    0
  Br3942_mid        0       0       0       0       0       0    0
  Br3942_post       0       0       0       0       0       0    0
  Br6423_ant        0       0       0       0       0       0    0
  Br6423_mid        0       0       0       0       0       0    0
  Br6423_post       0       0       0       0       0       0    0
  Br6432_ant        0       0       0       0       0       0    0
  Br6432_mid        0       0       0       0       0       0    0
  Br6432_post       0       0       0       0       0       0    0
  Br6471_ant        0       0       0       0       0       0    0
  Br6471_mid        0       0       0       0       0       0    0
  Br6471_post       0       0       0       0       0       0    0
  Br6522_ant      525     393     956     349     854     878  289
  Br6522_mid      359     380    1028     687     533     473  262
  Br6522_post       0       0       0       0       0       0    0
  Br8325_ant        0       0       0       0       0       0    0
  Br8325_mid        0       0       0       0       0       0    0
  Br8325_post       0       0       0       0       0       0    0
  Br8492_ant        0       0       0       0       0       0    0
  Br8492_mid        0       0       0       0       0       0    0
  Br8492_post       0       0       0       0       0       0    0
  Br8667_ant        0       0       0       0       0       0    0
  Br8667_mid        0       0       0       0       0       0    0
  Br8667_post       0     449    1553     761     875     387    0
```

Are there manual annotation for other slides? Thanks a lot!

**Comment by lcolladotor** [comment]
Hi @JiawenChenn,

In general, it's best to use `reprex::reprex()` as discussed in this video https://www.youtube.com/watch?v=8bBo3B7N8YQ. Check also https://reprex.tidyverse.org/.

Also, with `SpatialExperiment` objects, users are not supposed to use the `@` accessor function. I'm aware that `Seurat` encourages this practice, but in the Bioconductor world the advise is to not use `@`, as the internals of an object can change whereas the accessor functions such as `colData()` will follow https://contributions.bioconductor.org/deprecation.html and other guidelines that give users time to adjust code if needed.

Now, it seems that you are downloading the data from https://doi.org/10.1101/2023.02.15.528722 which has no manual annotations except for the 4 Visium ImmunoFluorescence (IF; also known as Visium SPG) samples. I believe that you wanted to download the data from https://doi.org/10.1038/s41593-020-00787-0. That is, `spatialLIBD::fetch_data("spe")` https://research.libd.org/spatialLIBD/reference/fetch_data.html.

Best,
Leo

**Comment by JiawenChenn** [comment]
Hi @lcolladotor,

Thanks a lot!! Thats really helpful.

Best,
Jiawen
