### ISSUE TITLE
Download of Histology Image of Visium(n=30) data

### ISSUE THREAD

**Issue by Weiqin-Zhao** [LieberInstitute/spatialDLPFC#145]
Dear Author,

Thank you for your excellent work!

May I know where I can access the histology images(*.tif) of the Visium(n=30) data?

In the adata_vis_orig.h5ad, the sample id of the Visium(n=30) data are:
{'Br2720_ant',
 'Br2720_mid',
 'Br2720_post',
 'Br2743_ant',
 'Br2743_mid',
 'Br2743_post',
 'Br3942_ant',
 'Br3942_mid',
 'Br3942_post',
 'Br6423_ant',
 'Br6423_mid',
 'Br6423_post',
 'Br6432_ant',
 'Br6432_mid',
 'Br6432_post',
 'Br6471_ant',
 'Br6471_mid',
 'Br6471_post',
 'Br6522_ant',
 'Br6522_mid',
 'Br6522_post',
 'Br8325_ant',
 'Br8325_mid',
 'Br8325_post',
 'Br8492_ant',
 'Br8492_mid',
 'Br8492_post',
 'Br8667_ant',
 'Br8667_mid',
 'Br8667_post'}

However, in the "/raw-data/Images/folder" in the globus link, I can only find Br2720 and Br6432.
I would be greatly appreciate if you could provide more assistance.

**Comment by Nick-Eagles** [comment]
Hello,

The images have a different naming convention than the `Br*` sample IDs, but all 30 images should be present under `/raw-data/Images`. The `/raw-data/sample_info/Visium_dlpfc_mastersheet.xlsx` Excel sheet has a `image file path` column that maps the expected sample IDs to their location on Globus, if you omit the beginning of each path up until `spatialDLPFC`. Please let me know if you're able to find everything given that information.

Best,
-Nick

**Comment by Weiqin-Zhao** [comment]
Thanks a lot! I have found the xlsx file!
