### ISSUE TITLE
Where can I get the full size H&E images?

### ISSUE THREAD

**Issue by amssljc** [LieberInstitute/spatialDLPFC#146]
Could you please give me a link to download 30 full size images or at least high resolution?
Thanks a lot! I cant connect to globus.

**Comment by lcolladotor** [comment]
Hi,

They are only available via Globus.

Best,
Leonardo

**Comment by lcolladotor** [comment]
Just to expand a bit, our data is hosted at JHPCE https://jhpce.jhu.edu/, which is down this week as noted at https://jhpce.jhu.edu/JHPCE-maintenance-july-2024/. So Globus will not work for a week or so, until JHPCE is back online again.

Best,
Leonardo

**Comment by amssljc** [comment]
@lcolladotor Thanks for the quick reply, I thought it was my internet, I'll try again after 7.22, thanks again!!!

**Comment by Yingxinzz** [comment]
Where can I get sce_DLPFC.Rdata?

**Comment by lcolladotor** [comment]
@Yingxinzz your question should have been a new issue as it's not related to H&E images.

It seems like you are interested in the SingleCellExperiment object for the snRNA-seq data from this project. If so, check the examples at https://research.libd.org/spatialLIBD/reference/fetch_data.html to see how you can download it with `spatialLIBD::fetch_data("spatialDLPFC_snRNAseq")`.

Best,
Leonardo
