### ISSUE TITLE
Spot deconvolution

### ISSUE THREAD

**Issue by tkcaccia** [LieberInstitute/spatialDLPFC#147]
Fantastic work.
In [https://github.com/LieberInstitute/spatialDLPFC/tree/main/processed-data/spot_deconvo](https://github.com/LieberInstitute/spatialDLPFC/tree/main/processed-data/spot_deconvo) you deconvolute the Visium spot for the 4 slides Br2720, Br6432, Br6522, Br8667. I was wondering if you have already done the spot deconvolution for your previous project that includes the Visium samples 151507, 151508, 151509, 151510, 151669, 151670, 151671, 151672, 151673, 151674, 151675, 151676. Are the deconvoluted spots downloadable somewhere?

Thank you in advance

**Comment by lcolladotor** [comment]
Hi @tkcaccia,

Thank you for your interest in our work. AFAIK we don't have spot deconvolution results from `SPOTlight`, `Tangram` or `cell2location` for the [`HumanPilot` project](https://github.com/LieberInstitute/HumanPilot).

But Nick can confirm this.

Best,
Leo

**Comment by Nick-Eagles** [comment]
Hello, unfortunately we haven't performed spot deconvolution on that data. Please feel free to reach out if there's anything else we can help with.

Best,
-Nick
