### ISSUE TITLE
raw-data/Images/VisiumIF is missing

### ISSUE THREAD

**Issue by randel** [LieberInstitute/spatialDLPFC#148]
Hi, thanks for developing this useful tool! I was looking for the .tif images files in raw-data/Images/VisiumIF, but the folder is missing. Is there a way to download raw images from spatialDLPFC_Visium_SPG? Thanks!

https://github.com/LieberInstitute/spatialDLPFC/tree/main/raw-data/Images

"VisiumIF: contains immunofluorescent images from n=4 samples and individual unmixed tiles from inForm"

"Images: raw images from the scanner in .tif format"

**Comment by lcolladotor** [comment]
See https://github.com/LieberInstitute/spatialDLPFC/issues/146#issuecomment-2231060760.

See also https://github.com/LieberInstitute/spatialDLPFC?tab=readme-ov-file#raw-data.

They are too big to be hosted on GitHub.

best,
Leo
