### ISSUE TITLE
Prepare to share files through spatialLIBD / ExperimentHub

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#76]
We'll expand `spatialLIBD::fetch_data()` such that users can download the new Visium and Visium IF data from this study. For each, we'll have an SPE object, a pseudo-bulked SCE one, and the modeling results from the pseudo-bulk analysis. For Visium IF we might only have an SPE object depending on whether we do any pseudo-bulk analysis with that data (for which we don't have plans as of today).

We'll first need to start creating the files that we'll share, like we did at `/dcl02/lieber/ajaffe/SpatialTranscriptomics/HumanPilot/Analysis/spatialLIBD_files` which was created with https://github.com/LieberInstitute/spatialLIBD/blob/master/inst/scripts/make-data_spatialLIBD.R.

We'll need to update https://github.com/LieberInstitute/spatialLIBD/blob/master/inst/scripts/make-metadata_spatialLIBD.R, which creates https://github.com/LieberInstitute/spatialLIBD/blob/master/inst/extdata/metadata_spatialLIBD.csv. See the `ExperimentHub` and `AnnotationHub` documentation vignettes in Bioconductor. 

Once we are close to submission, we'll need to get in touch with Bioconductor to get the AWS info to upload our files to ExperimentHub. Ultimately we'd like to say in the paper that you can download the data through`spatialLIBD::fetch_data()` / ExperimentHub + provide a Globus link to everything.

This will be reflected on the documentation files on the shiny app (#75) and the project README.md

**Comment by lcolladotor** [comment]
@Nick-Eagles what's the path for the IF data? Thanks again!

**Comment by Nick-Eagles** [comment]
`/dcs04/lieber/lcolladotor/spatialDLPFC_LIBD4035/spatialDLPFC/processed-data/spot_deconvo/05-shared_utilities/IF/spe.rds` or
```
here(
    "processed-data", "spot_deconvo", "05-shared_utilities", "IF", "spe.rds"
)
```

**Comment by lcolladotor** [comment]
Thanks!
