### ISSUE TITLE
Document internal directories

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#84]
Add README.md files at some of the internal directories. For example https://github.com/LieberInstitute/spatialDLPFC/tree/main/code but also within some `code` subdirectories. Do the same for `processed-data` and elsewhere. These README.md files don't have to be long, but they should explain a bit what is contained in them.

This will be useful for people checking this repo once it's public as well as those accessing files through Globus #83.

Have @joshstolz, @lahuuki, @Nick-Eagles or someone else check these files. You might want to list them all in a reply to this issue. Thanks!

Louise and Nick will have to make some themselves for the directories they are working on. @heenadivecha will have to make or help you make one or more for the Visium IF files.

**Comment by lcolladotor** [comment]
@Nick-Eagles @boyiguo1 @prashanthi-ravichandran do you have an update on this? Thanks!

**Comment by boyiguo1** [comment]
@lcolladotor Sorry, I was submitting the grant application. I will get this part done by next Monday lastest. Let me know if the timeline doesn't work. Thanks

**Comment by lcolladotor** [comment]
Boyi @boyiguo1, you mean by Monday 13th or 20th?

We'd like to submit to bioRxiv by Wed 15th, so maybe around Friday 17th people in the general public will start to notice our work and browse our repos. As you know, you can only create a good first impression once ;)

**Comment by lcolladotor** [comment]
@Nick-Eagles, can you schedule a meeting with @prashanthi-ravichandran so you can document her code? Or maybe she sent you a README.md already in her zip file with scripts?

**Comment by lcolladotor** [comment]
And good luck with your grant application Boyi! 🤞

**Comment by boyiguo1** [comment]
Sorry. I meant Monday 13th. The proposal was finished yesterday and sent out for Hopkins for review. So now I have the time to get the code documented/refactored.


> Boyi @boyiguo1, you mean by Monday 13th or 20th?
> 
> We'd like to submit to bioRxiv by Wed 15th, so maybe around Friday 17th people in the general public will start to notice our work and browse our repos. As you know, you can only create a good first impression once ;)

**Comment by lcolladotor** [comment]
Thanks!
